# Generated by Django 4.2.4 on 2024-03-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_file',
            field=models.FileField(default='dafault.mov', upload_to='user_video'),
        ),
    ]
